.*bitindex.s: Assembler messages:
.*bitindex.s:9: Error: number not in range 0-31 'bset d0,d1,#-1'
.*bitindex.s:10: Error: number not in range 0-31 'bset d0,d1,#33'
.*bitindex.s:11: Error: more than one bit set in bitmask 'bset d0,d1,#%bit\(5\)'
.*bitindex.s:12: Error: attempt to find bit index of 0 'bset d0,d1,#%bit\(0\)'
.*bitindex.s:13: Error: attempt to find bit index of 0 'bset d0,d1,#%bit\(0x100000000\)'
.*bitindex.s:14: Error: attempt to find bit index of 0 'bset d0,d1,#%msbbit\(0\)'
.*bitindex.s:15: Error: attempt to find bit index of 0 'bset d0,d1,#%lsbbit\(0\)'
