# Copyright (C) 2018 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston, MA 02110-1301, USA.  

if [istarget ubi32-*-*] then {
    run_dump_tests [lsort [glob -nocomplain $srcdir/$subdir/*.d]]

    run_list_test "bitindex" ""
    run_list_test "imm4" ""
    run_list_test "bit5" ""
    run_list_test "regsv61" "-mubi32v61"
    run_list_test "regsv5" "-mubi32v5"
    run_list_test "regsv4" "-mubi32v4"
    run_list_test "regsv3" "-mubi32v3"
    run_list_test "regsv2" "-mubi32v2"
}

